name: challenge_fudo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.11.0
  get_it: ^7.2.0
  go_router: ^5.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  hydrated_bloc: ^9.0.0
  mocktail: ^0.3.0
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: any

flutter_icons:
  image_path: "assets/favicon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/
